version: '3.5'
services:

  #APP
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - PHP_V=${PHP_V}
    container_name: ${APP_SID}-app
    restart: always
    links:
      - mysql
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ${APP_SRC}:/var/www/:cached
      - ./docker/utils/cron:/etc/cron
      - ./docker/utils/supervisor/conf.d:/etc/supervisor/conf.d
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  #NGINX
  nginx:
    image: nginx:alpine
    container_name: ${APP_SID}-nginx
    restart: always
    depends_on:
      - app
    links:
      - mysql
    tty: true
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ${APP_SRC}:/var/www/
      - ./docker/utils/cron:/etc/cron
      - ./docker/utils/supervisor/conf.d:/etc/supervisor/conf.d
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  #MYSQL
  mysql:
    image: mysql:${DB_VERS}
    container_name: ${APP_SID}-mysql
    restart: always
    tty: true
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password', '--innodb-use-native-aio=0']
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  #REDIS
  redis:
    image: redis:latest
    restart: always
    container_name: ${APP_SID}-redis
    expose:
      - 6379

  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_SID}-pma
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASS}

  #MAILHOG
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    container_name: ${APP_SID}-mailhog
    expose:
      - 1025
    ports:
      - ${MH_PORT}:8025